---

- name: ensure tasks run only on selected os releases
  block:

    - name: install virtualization packages
      ansible.builtin.package:
        name: "{{ kvm.packages }}"
        state: latest

    - name: enable nested virtualization
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/kvm.conf
        regexp: '^.*options kvm_amd nested'
        line: options kvm_amd nested=1
        create: true
        owner: root
        group: root
        mode: "0644"
      when: ansible_processor.1 == "AuthenticAMD"

    - name: enable nested virtualization
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/kvm.conf
        regexp: '^.*options kvm_intel nested'
        line: options kvm_intel nested=1
        create: true
        owner: root
        group: root
        mode: "0644"
      when: ansible_processor.1 == "GenuineIntel"

    - name: add kernel virtualization arguments
      ansible.builtin.include_role:
        name: mgmt__grub
        tasks_from: grubby.yml
      vars:
        kernel_arguments: "{{ kernel.arguments.amd }}"
      when: ansible_processor.1 == "AuthenticAMD"

    - name: add kernel virtualization arguments
      ansible.builtin.include_role:
        name: mgmt__grub
        tasks_from: grubby.yml
      vars:
        kernel_arguments: "{{ kernel.arguments.intel }}"
      when: ansible_processor.1 == "GenuineIntel"

    - name: enable and start the libvirt service
      ansible.builtin.service:
        name: libvirtd.socket
        state: started
        enabled: true

  when: >
    ansible_distribution == "CentOS" or
    ansible_distribution == "Fedora" or
    ansible_distribution == "RedHat" or
    ansible_distribution == "Rocky"

...
